apiVersion: v1
kind: Service
metadata:
  name: expense-tracker
  labels:
    app: expense-tracker
spec:
  type: LoadBalancer
  selector:
    app: expense-tracker
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: vnc
      port: 5900
      targetPort: 5900

